#!/usr/bin/env python3
"""Plot full-training PyG default vs custom SpMM comparisons."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


DATASET_ORDER = [
    "ogbn_arxiv",
    "ogbn_products",
    "flickr",
    "yelp",
    "amazon_products",
    "reddit",
]

DATASET_LABELS = {
    "ogbn_arxiv": "ogbn-arxiv",
    "ogbn_products": "ogbn-products",
    "flickr": "Flickr",
    "yelp": "Yelp",
    "amazon_products": "AmazonProducts",
    "reddit": "Reddit",
}

WORKLOADS = [
    ("neighbor_graphsage", "NeighborLoader + GraphSAGE"),
    ("cluster_gcn", "ClusterLoader + GCN"),
]

DEFAULT_COLOR = "#4C78A8"
OUR_COLOR = "#F58518"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot full-training wall/CUDA time comparisons"
    )
    parser.add_argument(
        "--summary-csv",
        default="results/full_training_spmm_compare/full_training_spmm_compare_summary.csv",
        help="CSV generated by tools/run_full_training_spmm_compare.py",
    )
    parser.add_argument(
        "--output-dir",
        default="results/full_training_spmm_compare/figures",
    )
    parser.add_argument(
        "--epoch",
        default="total",
        help="which epoch row to plot; default uses the aggregated total rows",
    )
    parser.add_argument("--dpi", type=int, default=400)
    parser.add_argument(
        "--linear",
        action="store_true",
        help="use a linear y-axis instead of the default log scale",
    )
    parser.add_argument(
        "--no-annotate",
        action="store_true",
        help="disable speedup labels above bars",
    )
    return parser.parse_args()


def configure_matplotlib() -> None:
    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": 400,
            "font.family": "DejaVu Sans",
            "font.size": 9,
            "axes.labelsize": 9,
            "axes.titlesize": 10,
            "legend.fontsize": 8,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "axes.linewidth": 0.8,
            "grid.linewidth": 0.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def load_rows(path: Path, epoch: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"missing summary CSV: {path}; run tools/run_full_training_spmm_compare.py first"
        )

    df = pd.read_csv(path)
    required = {
        "dataset",
        "workload",
        "epoch",
        "default_wall_ms",
        "our_wall_ms",
        "wall_speedup",
        "default_cuda_ms",
        "our_cuda_ms",
        "cuda_speedup",
    }
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"{path} missing required columns: {sorted(missing)}")

    out = df[df["epoch"].astype(str) == str(epoch)].copy()
    if out.empty:
        available = ", ".join(sorted(df["epoch"].astype(str).unique()))
        raise ValueError(f"no rows for epoch={epoch!r}; available epochs: {available}")

    out["dataset_order"] = out["dataset"].map(
        {name: idx for idx, name in enumerate(DATASET_ORDER)}
    )
    out["dataset_order"] = out["dataset_order"].fillna(len(DATASET_ORDER)).astype(int)
    return out.sort_values(["workload", "dataset_order", "dataset"])


def dataset_labels(part: pd.DataFrame) -> list[str]:
    return [DATASET_LABELS.get(dataset, dataset) for dataset in part["dataset"]]


def annotate_speedups(
    ax: plt.Axes,
    x_positions: list[float],
    default_values: list[float],
    our_values: list[float],
) -> None:
    for x, default, ours in zip(x_positions, default_values, our_values):
        if ours <= 0:
            continue
        speedup = default / ours
        y = max(default, ours)
        ax.annotate(
            f"{speedup:.2f}x",
            xy=(x, y),
            xytext=(0, 4),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=7,
            clip_on=False,
        )


def plot_metric(
    df: pd.DataFrame,
    output_dir: Path,
    stem: str,
    default_col: str,
    our_col: str,
    ylabel: str,
    dpi: int,
    log_scale: bool,
    annotate: bool,
) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.75), sharey=True)
    width = 0.36

    legend_handles = []
    legend_labels = []
    for ax, (workload, title) in zip(axes, WORKLOADS):
        part = df[df["workload"] == workload].sort_values(["dataset_order", "dataset"])
        if part.empty:
            ax.set_visible(False)
            continue

        labels = dataset_labels(part)
        x = list(range(len(labels)))
        default = part[default_col].astype(float).tolist()
        ours = part[our_col].astype(float).tolist()
        bars_default = ax.bar(
            [pos - width / 2 for pos in x],
            default,
            width,
            label="PyG default",
            color=DEFAULT_COLOR,
            edgecolor="black",
            linewidth=0.35,
        )
        bars_our = ax.bar(
            [pos + width / 2 for pos in x],
            ours,
            width,
            label="Our SpMM",
            color=OUR_COLOR,
            edgecolor="black",
            linewidth=0.35,
        )
        if not legend_handles:
            legend_handles = [bars_default[0], bars_our[0]]
            legend_labels = ["PyG default", "Our SpMM"]

        if annotate:
            annotate_speedups(ax, x, default, ours)

        ax.set_title(title)
        ax.set_xticks(x, labels)
        ax.tick_params(axis="x", rotation=24)
        for tick in ax.get_xticklabels():
            tick.set_horizontalalignment("right")
            tick.set_rotation_mode("anchor")
        if log_scale:
            ax.set_yscale("log")
        ax.grid(axis="y", which="both", alpha=0.28)
        ax.set_axisbelow(True)

    axes[0].set_ylabel(ylabel)
    fig.legend(
        legend_handles,
        legend_labels,
        loc="upper center",
        bbox_to_anchor=(0.5, 1.04),
        ncol=2,
        frameon=False,
    )
    fig.tight_layout(w_pad=1.3, rect=(0, 0, 1, 0.91))

    output_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_dir / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(output_dir / f"{stem}.png", bbox_inches="tight", dpi=dpi)
    plt.close(fig)


def main() -> int:
    args = parse_args()
    configure_matplotlib()
    output_dir = Path(args.output_dir)
    df = load_rows(Path(args.summary_csv), args.epoch)
    log_scale = not args.linear
    annotate = not args.no_annotate

    plot_metric(
        df,
        output_dir,
        stem="full_training_wall_time_compare",
        default_col="default_wall_ms",
        our_col="our_wall_ms",
        ylabel="Wall time (ms)",
        dpi=args.dpi,
        log_scale=log_scale,
        annotate=annotate,
    )
    plot_metric(
        df,
        output_dir,
        stem="full_training_cuda_time_compare",
        default_col="default_cuda_ms",
        our_col="our_cuda_ms",
        ylabel="CUDA time (ms)",
        dpi=args.dpi,
        log_scale=log_scale,
        annotate=annotate,
    )

    print(output_dir / "full_training_wall_time_compare.pdf")
    print(output_dir / "full_training_wall_time_compare.png")
    print(output_dir / "full_training_cuda_time_compare.pdf")
    print(output_dir / "full_training_cuda_time_compare.png")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
